version: "3.9"
services:
  ingester-local:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    # image: landscapedatacommons/ingester:latest
    stdin_open: true
    tty: true
    container_name: ingester
    volumes:
      - ./dimas:/usr/src/dimas
      # troubleshooting
      - ./debug3.py:/usr/src/debug3.py
      # - ./src/utils/database_functions.py:/usr/src/src/utils/database_functions.py
      # new development binds
      - ./index.py:/usr/src/index.py
      - ./src/utils/new_export.py:/usr/src/src/utils/new_export.py
      - ./src/utils/export.sh:/usr/src/src/utils/export.sh
      - ./src/utils/local_batch_utilities.py:/usr/src/src/utils/local_batch_utilities.py
      - ./src/utils/local_database_functions.py:/usr/src/src/utils/local_database_functions.py

#     networks:
#       - pg-network
# networks:
#   pg-network:
#     external: true
# docker-compose build
# docker-compose run --rm ingester
